
@authHeader = authtoken
@tokenUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImViaWViaUBlbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTYwOTQ5MzY4NywiZXhwIjoxNjA5NTgwMDg3fQ.ISh2x0bS9GJe-S4e0_hDCYZUquRHqXqFph08e-2eC0I
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTYwOTczNjU1NX0.KRy1h4-KhbmXXq02BM-8c9WP7IuyL5LVU5W24u28oE4

### commit users
GET http://localhost:9000/subs/commit/
{{authHeader}}:{{tokenAdmin}}

### drop users
GET http://localhost:9000/subs/drop/
{{authHeader}}:{{tokenAdmin}}

### get subs
GET http://localhost:9000/subs/
{{authHeader}}:{{tokenAdmin}}

### add subs
POST http://localhost:9000/subs/ HTTP/1.1
{{authHeader}}:{{tokenAdmin}}
content-type: application/json

{
    "userid": 1,
    "mangaid": 2
}
